language: erlang
otp_release:
  - 18.0
  - 17.0
  - R16B
script: make clean test
after_script:
    - ls
    - ./hex.sh
    - sh hex.sh
sudo: false
notifications:
  email:
    recipients:
      - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always

deploy:
  provider: script
  script: ./hex.sh
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
